---
# This is a declarative approach to describe a Kubernetes based
# deployment of an application.  Since this is YAML, the indentation
# is very important
apiVersion: apps/v1
kind: Deployment         # We are testing the Deployment resource
metadata:
  name: kafka-broker-deployment  # A name must be given to the deployment in the metadata section
spec:                     # This is the specification where we can even put the number of replicas
  replicas: 1             # Want two brokers
  selector:
    matchLabels:
      app: kafka-broker          # Basically this is like the search string used to locate the pods
  minReadySeconds: 5  # if anything crashes before 5 secs, the deployment is not
                          # considered as ready and available. Default value is 0
  template:               # Specified info needed to run the pod and what runs in the pod
    metadata:
      labels:
        app: kafka-broker        # some label to give to this pod (see the matching label above)
    spec:                 # actual specification
      hostname: kafka-broker-host  #this might need to be changed, not sure what this is 
      nodeSelector: 
       kubernetes.io/hostname: team16-ansible-vm2
      containers:
      - name: kafka-broker       # Used by DNS
        image: 129.114.25.102:5000/kafka-dockerfile
        ports: 
         - containerPort: 9092
        imagePullPolicy: IfNotPresent
        command: ["kafka_2.13-2.6.0/bin/kafka-server-start.sh"]
        args: ["kafka_2.13-2.6.0/config/server.properties", "--override", "brokerid = 0", "--override", "listeners=PLAINTEXT://9092", "--override", "advertised.listeners=PLAINTEXT://129.114.25.102:0000", "--override", "listeners.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL", "--override", "zookeeper.connect=zookeeper-service:2181"]
 
...
